require 'rubygems'
require 'railsless-deploy'
load 'config/deploy.rb' if respond_to?(:namespace)

desc "Setup Nginx and Thin"
task :setup do
	run "#{deploy_to}/current/scripts/setup.sh"
end

desc "Configure Nginx and Thin"
task :config do
	run "#{deploy_to}/current/scripts/config.sh"
end

desc "start nginx"
task :start_nginx do
	run "sudo /sbin/service nginx start"
end

desc "stop nginx"
task :stop_nginx do
	run "sudo /sbin/service nginx stop"
end

desc "restart nginx"
task :restart_nginx do
	run "sudo /sbin/service nginx restart"
	run "sudo chown ec2-user /u/myapp/current/log/*"
end

desc "start thin"
task :start_thin do
	run "#{deploy_to}/current/scripts/start_thin.sh"
end

desc "stop thin"
task :stop_thin do
	run "#{deploy_to}/current/scripts/stop_thin.sh"
end

desc "restart thin"
task :restart_thin do
	run "#{deploy_to}/current/scripts/restart_thin.sh"
end
