#!/bin/bash
#
# Startup script for Icecast
#
# chkconfig: 345 85 15
# description: icecast

# Source function library.
. /etc/rc.d/init.d/functions

prog=icecast
pidfile=${PIDFILE-/usr/local/share/icecast/icecast.pid}
RETVAL=0

case "$1" in
start)
      # Start daemon.
      echo -n "Starting $prog: "
      /usr/local/bin/icecast -c /u/etc/icecast.xml > /dev/null 2>&1 &
      RETVAL=$?
      echo
      ;;
stop)
      echo -n $"Stopping $prog: "
      kill `cat ${pidfile}`
      RETVAL=$?
      echo
      [ $RETVAL = 0 ] && rm -f ${pidfile}
      ;;
restart)
      $0 stop
      $0 start
      ;;
*)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
esac

exit $RETVAL
