require 'rubygems'
require 'railsless-deploy'
load 'config/deploy.rb' if respond_to?(:namespace)

desc "Echo the server's hostname"
task :echo_hostname do 
  run "echo `hostname`"
end

desc "Echo the server's hostname"
task :hostname do 
  run "hostname"
end

desc "Echo the user's name"
task :whoami do 
  run "whoami"
  run "rvm current"
  run "gem list"
end

desc "Echo the sudo user's name"
task :sudo_whoami do 
  run "sudo whoami"
end
