require 'rubygems'
require 'railsless-deploy'
load 'config/deploy.rb' if respond_to?(:namespace)

desc "Install Thin Gemset"
task :setup do
	run "#{deploy_to}/current/scripts/setup.sh"
end

desc "Install Thin Server"
task :thin_install do
	run "sudo #{deploy_to}/current/scripts/thin_install.sh"
end
