require 'rubygems'
require 'railsless-deploy'
load 'config/deploy.rb' if respond_to?(:namespace)

desc "yum install nginx"
task :yum_nginx do
	run "sudo yum -y install nginx.i686"
end

desc "start nginx"
task :start_nginx do
	run "sudo service nginx start"
end

desc "stop nginx"
task :stop_nginx do
	run "sudo service nginx stop"
end

desc "restart nginx"
task :restart_nginx do
	run "sudo service nginx restart"
end
